class main {
public:

};

// indexHtml_part1 + x*indexHtml_partRawItem + indexHtml_part2
#define indexHtml_part1 "<!DOCTYPE html><html><head> <meta http-equiv=\"content-type\" content=\"text/html; charset=windows-1252\"> <title>ESP32-Cam WiFiSetup</title> <link rel=\"stylesheet\" type=\"text/css\" href=\"/style.css\"></head><body> <header> <h1>ESP32 Camera</h1> </header> <div class=\"box\"> <h1>WiFi-Setup</h1> <table class=\"wifiListTable\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\"> <tbody>"

// then add items to table - substitute WIFI_ID & WIFI_NAME
#define indexHtml_partRawItem "<tr> <td style=\"border: 0\" class=\"tdName\"> <h3 id=\"WIFI_ID\">WIFI_NAME</h3> </td><td style=\"border: 0\" class=\"tdButton\"> <button id=\"button\" type=\"button\" onClick=\"showPopup(WIFI_ID.textContent)\" class=\"selectWifiButton\">Connect to it!</button> </td></tr>"



#define indexHtml_hr_line "<tr> <td colspan=\"2\"> <hr> </td></tr>"
#define indexHtml_part2 "</tbody> </table> </div> <div class=\"popup_overlay\" style=\"width: 100%; height: 100%;\"> <div class=\"popup-content\"> <h1 id=\"popupWifiName\" style=\"color: white;\">nameplaceholder</h1> <input id=\"wifiName\" type=\"hidden\" name=\"networkName\" value=\"\" /> <h5 style=\"color: white;\">Please put in below the password of the network to connect.</h5> <div class=\"part\"> <input id=\"inputPassword\" class=\"inputPassword\" required=\"required\" placeholder=\"Password\" name=\"networkPassword\" value=\"\" type=\"password\"> <label id=\"errorLabel\" class=\"errorLabel\">Incorrect WiFi password.</label> </div> <button type=\"button\" class=\"connectToWifiButton\" onClick=\"connectToWiFi()\">Connect!</button> <div style=\"width: 100%; height: 100%; display: flex; justify-content: end;\"> <button type=\"button\" class=\"closePopupButton\" onClick=\"closePopup()\">X</button> </div> </div> </div> <div class=\"loader_overlay\" style=\"width: 100%; height: 100%;\"> <div class=\"loader-content\"> </div> </div> <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\" integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\" crossorigin=\"anonymous\"></script> <script type=\"text/javascript\"> function showPopup(stringwifi) { $(\".popup_overlay\").hide().fadeIn(300); document.getElementById(\"popupWifiName\").textContent = stringwifi; document.getElementById(\"wifiName\").value = stringwifi; document.getElementById(\"inputPassword\").value = \"\"; $(\".errorLabel\").hide(0); } function closePopup() { $(\".popup_overlay\").fadeOut(300); } function showLoading() { if (document.getElementById(\"inputPassword\").value != \"\") { $(\".loader_overlay\").fadeIn(100); } } function hideLoading() { $(\".loader_overlay\").fadeOut(300); } function showPasswordError() { console.log(\"SHOW PASSWORD ERROR LABEL\"); $(\".errorLabel\").show().delay(10000).fadeOut(); } function connectToWiFi() { showLoading(); sendWiFiCredentials(); } function sendWiFiCredentials() { if (document.getElementById(\"inputPassword\").value != \"\") { var xhttp = new XMLHttpRequest(); xhttp.open(\"POST\", \"connectWiFi\", true); xhttp.setRequestHeader('Content-type', 'application/x-www-form-urlencoded'); xhttp.onreadystatechange = function () { if (xhttp.readyState == 4 && xhttp.status == 200) { $(\"body\").html(xhttp.responseText); } else if (xhttp.readyState == 4 && xhttp.status == 401) { console.log(xhttp.responseText); hideLoading(); showPasswordError(); } }; var nameAndPasswort = \"networkName=\" + document.getElementById(\"wifiName\").value + \"&networkPassword=\" + document.getElementById(\"inputPassword\").value; xhttp.send(nameAndPasswort); } } </script> </body> </html>"
